######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 26 21:31:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += dhtserver.h
FORMS += dhtserver.ui
SOURCES += dhtserver.cpp main.cpp
CONFIG += crypto
